apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-balance-deployment
spec:
  selector:
    matchLabels:
      app: account-balance
  replicas: 1
  template:
    metadata:
      labels:
        app: account-balance
        env: test
    spec:
      containers:
        - name: account-balance
          image: registry.cn-hangzhou.aliyuncs.com/happyboy/hstc-demo:latest
          args: ["--spring.profiles.active=prod"]
          hpa:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 60
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SECRET_DB_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: noshow
                    key: db_username
            - name: SECRET_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: noshow
                    key: db_password
            - name: SECRET_DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: noshow
                    key: db_host
            - name: SECRET_REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: noshow
                    key: redis_password
            - name: SECRET_REDIS_HOST
                valueFrom:
                  secretKeyRef:
                    name: noshow
                    key: redis_host
#          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: account-balance
spec:
  selector:
    app: account-balance
    env: test
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082